ALTER TABLE `Prompt`
  ADD COLUMN `seoFocusKeyword` VARCHAR(191) NULL,
  ADD COLUMN `seoCanonicalUrl` LONGTEXT NULL,
  ADD COLUMN `seoNoIndex` BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE `Post`
  ADD COLUMN `seoFocusKeyword` VARCHAR(191) NULL,
  ADD COLUMN `seoCanonicalUrl` LONGTEXT NULL,
  ADD COLUMN `seoNoIndex` BOOLEAN NOT NULL DEFAULT FALSE;
