CREATE TABLE `RedirectRule` (
  `id` VARCHAR(191) NOT NULL,
  `sourcePath` VARCHAR(512) NOT NULL,
  `destinationPath` VARCHAR(2048) NOT NULL,
  `isPermanent` BOOLEAN NOT NULL DEFAULT TRUE,
  `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
  `hitCount` INT NOT NULL DEFAULT 0,
  `lastHitAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `RedirectRule_sourcePath_key` (`sourcePath`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
