ALTER TABLE `SeoSettings`
  ADD COLUMN `noindexBlogArchivePages` BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN `noindexBlogPostPages` BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN `noindexStaticPages` BOOLEAN NOT NULL DEFAULT FALSE;
