ALTER TABLE `SeoSettings`
  ADD COLUMN `schemaWebPageEnabled` BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN `schemaFaqEnabled` BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN `schemaCollectionEnabled` BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN `schemaPromptEnabled` BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN `schemaSearchEnabled` BOOLEAN NOT NULL DEFAULT TRUE;
