import type { DashboardSeoSettings } from './types';
import type { DashboardSeoIntegrationSettings } from './types';

export const DEFAULT_DASHBOARD_SEO_SETTINGS: DashboardSeoSettings = {
  siteTitle: 'Gemini Prompts',
  titleSeparator: '|',
  defaultMetaDescription:
    'Discover curated AI prompts, practical workflows, creator guides, and weekly prompt drops.',
  homepageTitle: null,
  homepageDescription: null,
  defaultOgImageUrl: null,
  defaultOgImageAlt: null,
  twitterCardType: 'summary_large_image',
  schemaOrganizationEnabled: true,
  schemaWebsiteEnabled: true,
  schemaWebPageEnabled: true,
  schemaFaqEnabled: true,
  schemaCollectionEnabled: true,
  schemaArticleEnabled: true,
  schemaProfileEnabled: true,
  schemaBreadcrumbEnabled: true,
  schemaPromptEnabled: true,
  schemaSearchEnabled: true,
  robotsSiteIndex: true,
  robotsSiteFollow: true,
  robotsBlockAiBots: false,
  robotsDisallowPaths: ['/dashboard', '/login', '/profile'],
  robotsAdditionalRules: [],
  robotsCustomText: null,
  sitemapIncludePrompts: true,
  sitemapIncludePages: true,
  sitemapIncludePosts: true,
  sitemapIncludeNewsletter: true,
  sitemapIncludeTags: true,
  sitemapIncludeCategories: true,
  sitemapIncludeAuthors: true,
  sitemapCustomXml: null,
  canonicalBaseUrl: null,
  googleSiteVerification: null,
  bingSiteVerification: null,
  organizationName: null,
  organizationLogoUrl: null,
  organizationSameAs: [],
  noindexSearchPages: true,
  noindexPaginatedArchives: true,
  noindexAuthorPages: false,
  noindexTagPages: false,
  noindexCategoryPages: false,
  noindexBlogArchivePages: false,
  noindexBlogPostPages: false,
  noindexStaticPages: false,
};

export const DEFAULT_DASHBOARD_SEO_INTEGRATIONS: DashboardSeoIntegrationSettings = {
  scope: 'production',
  googleSiteVerification: null,
  bingSiteVerification: null,
  gaMeasurementId: null,
  googleAdsTagId: null,
  adsensePublisherId: null,
  clarityProjectId: null,
  customHeadScriptUrls: [],
  customHeadInlineScript: null,
  customHeadInlineStyle: null,
  customBodyStartInlineScript: null,
  customBodyEndInlineScript: null,
  updatedByUserId: null,
};
